baseURL = "https://arcanecodex.dev/"
languageCode = 'en-us'
title = 'Arcane Codex'
theme = 'ArcaneCodex'
enableRobotsTXT = true

[params]
  env = "production"
  defaultTheme = "dark" 
  ShowReadingTime = true
  ShowShareButtons = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
