baseURL = getenv("HUGO_BASEURL", "https://arcanecodex.dev/")
languageCode = 'en-us'
title = 'Arcane Codex'
theme = 'PaperMod'
enableRobotsTXT = getenv("HUGO_ENABLE_ROBOTS", "true") | eq "true"

[params]
  env = getenv("HUGO_ENV", "production")
  defaultTheme = "dark" 
  ShowReadingTime = true
  ShowShareButtons = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
