baseURL = "https://arcanecodex.dev/"
languageCode = 'en-us'
title = 'Arcane Codex' 
theme = 'ArcaneCodex'
enableRobotsTXT = true

[params]
  description = "Compiled Texts for Modern Mage | A chronicle of digital sorcery, technical guides, thoughts, and experiences."
  author = "The Arcane Dev | Sumeet Saini"
  defaultTheme = "dark" 
  ShowReadingTime = true
  ShowShareButtons = true
  disableThemeToggle = true
  disableFingerprinting = true
  disableScrollToTop = true
  hideAuthor = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"] 
  section = ["HTML"]
  taxonomy = ["HTML"] 
  term = ["HTML"]

[params.assets]
favicon = "favicon.ico"
logo = "logo.png"
ogImage = "ogImage.png"

[taxonomies]
  category = "categories"
  tag = "tags"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[menu]
  [[menu.main]]
    identifier = "search"
    name = ""
    post = '<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg> '
    url = "/search/"
    weight = 5
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 7
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 8
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 20
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 30
